default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: o-meu-chapa_development

test:
  <<: *default
  database: o-meu-chapa_test
